### ISSUE TITLE
Fix: default random positions for robots

### ISSUE THREAD

**Issue by KajaKoren** [NordicPlayground/robot-war-app#15]
Default random positions for robots on admin page. The first time I used my own access key, the robots positions went crazy on the admin page for each update, randomly moving them everywhere, it was first when I selected the positions for the robots that they stood still until I moved them again. Some kind of default random set positions for the robots could be the solution.

**Comment by coderbyheart** [comment]
Done via deed337e6dda8c85ba3428134a8f761c4f1dfdbe
