### ISSUE TITLE
Reset admin shadow

### ISSUE THREAD

**Issue by MLopezJ** [NordicPlayground/robot-war-app#37]
Right now, there are buttons in `game controller` view to reset the reported and desired shadow, those buttons were added for testing proposes. With the same intention of testing the game by smoke testing, a `reset admin shadow` button should be added on that view. This way we can reset the admin shadow when needed with out the need of interrupt @Lenakh97  to reset it her manually.

**Comment by coderbyheart** [comment]
Done via 43b6c08750e3a392add3956be2b556fe978f6b0f
